package util

import (
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/labstack/gommon/log"
	"github.com/ngoduykhanh/wireguard-ui/model"
	"github.com/ngoduykhanh/wireguard-ui/store"
)

// WriteInterfaceConfig writes the WireGuard configuration for a specific interface
func WriteInterfaceConfig(tmplDir fs.FS, iface model.WgInterface, clients []model.ClientData, 
	users []model.User, globalSettings model.GlobalSetting) error {
	
	// Ensure directory exists
	configDir := filepath.Dir(iface.ConfigFilePath)
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("cannot create config directory: %v", err)
	}

	// write config file to disk
	f, err := os.Create(iface.ConfigFilePath)
	if err != nil {
		return err
	}
	defer f.Close()

	// For client-type interfaces, generate a simple client config
	if iface.Type == model.WgInterfaceTypeClient {
		return writeClientInterfaceConfig(f, iface)
	}

	// For server-type interfaces, use the template system
	var tmplWireguardConf string

	// if set, read wg.conf template from WgConfTemplate
	if len(WgConfTemplate) > 0 {
		fileContentBytes, err := os.ReadFile(WgConfTemplate)
		if err != nil {
			return err
		}
		tmplWireguardConf = string(fileContentBytes)
	} else {
		// read default wg.conf template file to string
		fileContent, err := StringFromEmbedFile(tmplDir, "wg.conf")
		if err != nil {
			return err
		}
		tmplWireguardConf = fileContent
	}

	// escape multiline notes for clients
	escapedClientDataList := []model.ClientData{}
	for _, cd := range clients {
		if cd.Client != nil && cd.Client.AdditionalNotes != "" {
			cd.Client.AdditionalNotes = strings.ReplaceAll(cd.Client.AdditionalNotes, "\n", "\n# ")
		}
		escapedClientDataList = append(escapedClientDataList, cd)
	}

	// parse the template
	t, err := template.New("wg_config").Parse(tmplWireguardConf)
	if err != nil {
		return err
	}

	// Determine script paths for this interface
	// Note: configDir is already declared on line 21
	configDir = filepath.Dir(iface.ConfigFilePath)
	if configDir == "" || configDir == "." {
		configDir = "/etc/wireguard"
	}
	
	// For wg0 (default interface), use standard postup.sh/postdown.sh names
	// For other interfaces, use interface-specific names
	var postUpPath, postDownPath string
	if iface.ID == "wg0" || iface.IsDefault {
		// Use default/global script names for wg0 to avoid confusion
		if globalSettings.PostUpScriptPath != "" {
			postUpPath = globalSettings.PostUpScriptPath
		} else {
			postUpPath = filepath.Join(configDir, "postup.sh")
		}
		if globalSettings.PostDownScriptPath != "" {
			postDownPath = globalSettings.PostDownScriptPath
		} else {
			postDownPath = filepath.Join(configDir, "postdown.sh")
		}
	} else {
		// Use interface-specific script names for non-default interfaces
		postUpPath = filepath.Join(configDir, iface.ID+"-postup.sh")
		postDownPath = filepath.Join(configDir, iface.ID+"-postdown.sh")
	}

	// Build server config from interface for template compatibility
	// PostUp/PostDown are file paths (not script content) - they're written to WireGuard config
	serverConfig := model.Server{
		KeyPair: &model.ServerKeypair{
			PrivateKey: iface.PrivateKey,
			PublicKey:  iface.PublicKey,
		},
		Interface: &model.ServerInterface{
			Addresses:  iface.InterfaceAddresses,
			ListenPort: iface.ListenPort,
			PostUp:     postUpPath,
			PostDown:   postDownPath,
		},
	}

	config := map[string]interface{}{
		"serverConfig":   serverConfig,
		"clientDataList": escapedClientDataList,
		"globalSettings": globalSettings,
		"usersList":      users,
		"interface":      iface, // Pass interface object for Table directive
	}

	err = t.Execute(f, config)
	if err != nil {
		return err
	}

	// Ensure the file has proper permissions
	if err := ManagePerms(iface.ConfigFilePath); err != nil {
		return err
	}

	return nil
}

// writeClientInterfaceConfig writes a WireGuard client configuration
func writeClientInterfaceConfig(f *os.File, iface model.WgInterface) error {
	var config strings.Builder
	
	config.WriteString("# Generated by wireguard-ui for client interface " + iface.ID + "\n")
	config.WriteString("# Name: " + iface.Name + "\n")
	config.WriteString("# Please don't modify it manually, otherwise your change might get replaced.\n\n")
	
	config.WriteString("[Interface]\n")
	
	// Address
	if len(iface.InterfaceAddresses) > 0 {
		config.WriteString("Address = " + strings.Join(iface.InterfaceAddresses, ",") + "\n")
	}
	
	// PrivateKey
	config.WriteString("PrivateKey = " + iface.PrivateKey + "\n")
	
	// DNS
	if len(iface.DNS) > 0 {
		config.WriteString("DNS = " + strings.Join(iface.DNS, ",") + "\n")
	}
	
	// MTU
	if iface.MTU > 0 {
		config.WriteString(fmt.Sprintf("MTU = %d\n", iface.MTU))
	}
	
	// Table directive for client interfaces
	if iface.Table != "" {
		config.WriteString("Table = " + iface.Table + "\n")
	}
	
	// PostUp/PostDown - always add for client interfaces to support inter-interface routing
	configDir := filepath.Dir(iface.ConfigFilePath)
	if configDir == "" || configDir == "." {
		configDir = "/etc/wireguard"
	}
	postUpPath := filepath.Join(configDir, iface.ID+"-postup.sh")
	postDownPath := filepath.Join(configDir, iface.ID+"-postdown.sh")
	
	config.WriteString("PostUp = " + postUpPath + "\n")
	config.WriteString("PostDown = " + postDownPath + "\n")
	
	// Peer section
	config.WriteString("\n[Peer]\n")
	config.WriteString("PublicKey = " + iface.PeerPublicKey + "\n")
	
	if iface.PeerPresharedKey != "" {
		config.WriteString("PresharedKey = " + iface.PeerPresharedKey + "\n")
	}
	
	if iface.PeerEndpoint != "" {
		config.WriteString("Endpoint = " + iface.PeerEndpoint + "\n")
	}
	
	if len(iface.PeerAllowedIPs) > 0 {
		config.WriteString("AllowedIPs = " + strings.Join(iface.PeerAllowedIPs, ",") + "\n")
	}
	
	if iface.PeerPersistentKeepalive > 0 {
		config.WriteString(fmt.Sprintf("PersistentKeepalive = %d\n", iface.PeerPersistentKeepalive))
	}
	
	_, err := f.WriteString(config.String())
	return err
}

// GenerateAndSaveInterfaceScripts generates and saves PostUp/PostDown scripts for a specific interface
func GenerateAndSaveInterfaceScripts(db store.IStore, interfaceID string, iface model.WgInterface, 
	globalSettings model.GlobalSetting, firewallRules []model.FirewallRule, clients []model.ClientData) error {
	
	// Calculate WG_SUBNETS from interface addresses
	wgSubnets := strings.Join(iface.InterfaceAddresses, ",")

	// Get all interfaces for inter-interface routing
	allInterfaces, err := db.GetInterfaces()
	if err != nil {
		log.Warnf("Cannot get all interfaces for routing config: %v", err)
		allInterfaces = []model.WgInterface{}
	}

	// Generate PostUp script with routing support
	postUpScript := GeneratePostUpScriptWithRouting(globalSettings, wgSubnets, firewallRules, clients, interfaceID, &iface, allInterfaces)
	
	// Generate PostDown script with routing support
	postDownScript := GeneratePostDownScriptWithRouting(globalSettings, wgSubnets, firewallRules, clients, interfaceID, &iface, allInterfaces)

	// Determine script paths - use interface-specific paths for non-default interfaces
	configDir := filepath.Dir(iface.ConfigFilePath)
	if configDir == "" || configDir == "." {
		configDir = "/etc/wireguard"
	}

	// For wg0 (default interface), use standard postup.sh/postdown.sh names
	// For other interfaces, use interface-specific names
	var postUpPath, postDownPath string
	if interfaceID == "wg0" || iface.IsDefault {
		// Use default/global script names for wg0 to avoid confusion with existing setup
		if globalSettings.PostUpScriptPath != "" {
			postUpPath = globalSettings.PostUpScriptPath
		} else {
			postUpPath = filepath.Join(configDir, "postup.sh")
		}
		if globalSettings.PostDownScriptPath != "" {
			postDownPath = globalSettings.PostDownScriptPath
		} else {
			postDownPath = filepath.Join(configDir, "postdown.sh")
		}
	} else {
		// Use interface-specific script names for non-default interfaces
		postUpPath = filepath.Join(configDir, interfaceID+"-postup.sh")
		postDownPath = filepath.Join(configDir, interfaceID+"-postdown.sh")
	}

	// Write PostUp script
	if err := os.WriteFile(postUpPath, []byte(postUpScript), 0755); err != nil {
		return fmt.Errorf("cannot write PostUp script: %v", err)
	}

	// Write PostDown script
	if err := os.WriteFile(postDownPath, []byte(postDownScript), 0755); err != nil {
		return fmt.Errorf("cannot write PostDown script: %v", err)
	}

	log.Infof("Generated scripts for interface %s: %s, %s", interfaceID, postUpPath, postDownPath)

	return nil
}

// ApplyInterfaceConfig applies configuration for a specific interface
func ApplyInterfaceConfig(db store.IStore, tmplDir fs.FS, interfaceID string) error {
	// Get the interface
	iface, err := db.GetInterface(interfaceID)
	if err != nil {
		return fmt.Errorf("cannot get interface %s: %v", interfaceID, err)
	}

	// Get clients for this interface
	clients, err := db.GetClientsByInterface(interfaceID, false)
	if err != nil {
		return fmt.Errorf("cannot get clients for interface %s: %v", interfaceID, err)
	}

	// Get users (needed for template)
	users, err := db.GetUsers()
	if err != nil {
		return fmt.Errorf("cannot get users: %v", err)
	}

	// Get global settings
	settings, err := db.GetGlobalSettings()
	if err != nil {
		return fmt.Errorf("cannot get global settings: %v", err)
	}

	// Get firewall rules for this interface
	firewallRules, err := db.GetFirewallRulesByInterface(interfaceID)
	if err != nil {
		log.Warnf("Cannot get firewall rules for interface %s (will proceed without them): %v", interfaceID, err)
		firewallRules = []model.FirewallRule{}
	}

	// Write interface config file
	if err := WriteInterfaceConfig(tmplDir, iface, clients, users, settings); err != nil {
		return fmt.Errorf("cannot write config for interface %s: %v", interfaceID, err)
	}

	// Generate and save scripts
	if err := GenerateAndSaveInterfaceScripts(db, interfaceID, iface, settings, firewallRules, clients); err != nil {
		return fmt.Errorf("cannot generate scripts for interface %s: %v", interfaceID, err)
	}

	// Don't auto-restart here - let admin use Apply Config button to avoid race conditions
	// This prevents conflicts with init.sh monitoring
	log.Infof("Config and scripts generated for interface %s. Use 'Apply Config' button to restart if needed.", interfaceID)

	return nil
}

// RestartInterface restarts a WireGuard interface
func RestartInterface(interfaceID string) error {
	confPath := filepath.Join("/etc/wireguard", interfaceID+".conf")
	
	// Check if config file exists
	if _, err := os.Stat(confPath); os.IsNotExist(err) {
		return fmt.Errorf("config file does not exist: %s", confPath)
	}
	
	// Check if interface is currently running
	checkCmd := exec.Command("wg", "show", interfaceID)
	isRunning := checkCmd.Run() == nil
	
	if isRunning {
		// Stop the interface
		log.Infof("Stopping interface %s", interfaceID)
		stopCmd := exec.Command("wg-quick", "down", confPath)
		stopCmd.Stdout = os.Stdout
		stopCmd.Stderr = os.Stderr
		if err := stopCmd.Run(); err != nil {
			log.Warnf("Error stopping interface %s: %v", interfaceID, err)
		}
		
		// Give it more time to fully stop and release resources
		time.Sleep(1 * time.Second)
		
		// Verify interface is down
		for i := 0; i < 3; i++ {
			checkCmd = exec.Command("wg", "show", interfaceID)
			if checkCmd.Run() != nil {
				// Interface is down
				break
			}
			// Still exists, wait a bit more
			time.Sleep(500 * time.Millisecond)
		}
		
		// If still exists after multiple checks, force remove it
		checkCmd = exec.Command("wg", "show", interfaceID)
		if checkCmd.Run() == nil {
			log.Warnf("Interface %s still exists after stop, forcing down", interfaceID)
			exec.Command("ip", "link", "delete", interfaceID).Run()
			time.Sleep(500 * time.Millisecond)
		}
	}
	
	// Start the interface
	log.Infof("Starting interface %s", interfaceID)
	startCmd := exec.Command("wg-quick", "up", confPath)
	startCmd.Stdout = os.Stdout
	startCmd.Stderr = os.Stderr
	if err := startCmd.Run(); err != nil {
		return fmt.Errorf("failed to start interface: %v", err)
	}
	
	log.Infof("Successfully restarted interface %s", interfaceID)
	return nil
}

// ApplyAllInterfacesConfig applies configuration for all enabled interfaces
func ApplyAllInterfacesConfig(db store.IStore, tmplDir fs.FS) error {
	interfaces, err := db.GetInterfaces()
	if err != nil {
		return fmt.Errorf("cannot get interfaces: %v", err)
	}

	// Apply config for each enabled interface
	for _, iface := range interfaces {
		if !iface.Enabled {
			log.Infof("Skipping disabled interface: %s", iface.ID)
			continue
		}

		log.Infof("Applying configuration for interface: %s", iface.ID)
		if err := ApplyInterfaceConfig(db, tmplDir, iface.ID); err != nil {
			// Log error but continue with other interfaces
			log.Errorf("Failed to apply config for interface %s: %v", iface.ID, err)
		}
	}

	return nil
}
